// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv-Yi62oDiyazb9Qn7mGJpsLOHMWAgn4g',
    appId: '1:649825161135:web:33740d7a791fe7fc67295a',
    messagingSenderId: '649825161135',
    projectId: 'stalkin-e5344',
    authDomain: 'stalkin-e5344.firebaseapp.com',
    storageBucket: 'stalkin-e5344.appspot.com',
    measurementId: 'G-T28FJ384H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpaBSzYyTCWnoFgHv0UeytcCl-k1idBD8',
    appId: '1:649825161135:android:0825f5969bcc11e767295a',
    messagingSenderId: '649825161135',
    projectId: 'stalkin-e5344',
    storageBucket: 'stalkin-e5344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfafSW5zD-CneY8M5MFEA1Qd-lMhClzZY',
    appId: '1:649825161135:ios:b766fc762d28999c67295a',
    messagingSenderId: '649825161135',
    projectId: 'stalkin-e5344',
    storageBucket: 'stalkin-e5344.appspot.com',
    iosClientId: '649825161135-jle2v6ts2k6rr3e7fgjmr6vj7ej6mi9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.stalkin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfafSW5zD-CneY8M5MFEA1Qd-lMhClzZY',
    appId: '1:649825161135:ios:b766fc762d28999c67295a',
    messagingSenderId: '649825161135',
    projectId: 'stalkin-e5344',
    storageBucket: 'stalkin-e5344.appspot.com',
    iosClientId: '649825161135-jle2v6ts2k6rr3e7fgjmr6vj7ej6mi9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.stalkin',
  );
}
